SET FOREIGN_KEY_CHECKS = 0;
CREATE DATABASE IF NOT EXISTS research_lab;
USE research_lab;

-- 1. ENTITIES

CREATE TABLE IF NOT EXISTS GRANT_INFO (
    GID INT PRIMARY KEY AUTO_INCREMENT, -- Auto-increment added
    Source VARCHAR(255),
    Budget DECIMAL(15,2),
    StartDate DATE,
    Duration INT
);

-- Note: We set the starting value in the INSERT script later if needed, 
-- or let the manual inserts override it (MySQL allows this).

CREATE TABLE IF NOT EXISTS PROJECT (
    PID INT PRIMARY KEY AUTO_INCREMENT, -- Auto-increment added
    Title VARCHAR(255),
    SDate DATE,
    EDate DATE,
    EDuration INT,
    Leader INT NULL -- Nullable: If Faculty leaves, project keeps running
);

CREATE TABLE IF NOT EXISTS LAB_MEMBER (
    MID INT PRIMARY KEY AUTO_INCREMENT, -- Auto-increment added
    Name VARCHAR(255),
    JoinDate DATE,
    MType VARCHAR(50), 
    Mentor INT NULL,
    FOREIGN KEY (Mentor) REFERENCES LAB_MEMBER(MID) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS EQUIPMENT (
    EID INT PRIMARY KEY AUTO_INCREMENT, -- Auto-increment added
    EType VARCHAR(100),
    EName VARCHAR(100),
    Status VARCHAR(50),
    PDate DATE
);

CREATE TABLE IF NOT EXISTS PUBLICATION (
    PubID INT PRIMARY KEY AUTO_INCREMENT, -- Auto-increment added
    Title VARCHAR(255),
    Venue VARCHAR(255),
    Date DATE,
    DOI VARCHAR(255) NULL
);

-- 2. SUB-CLASSES (No Auto-Increment here, they share MID from LAB_MEMBER)
CREATE TABLE IF NOT EXISTS STUDENT (
    MID INT PRIMARY KEY,
    SID INT,
    Level VARCHAR(50),
    Major VARCHAR(100),
    FOREIGN KEY (MID) REFERENCES LAB_MEMBER(MID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FACULTY (
    MID INT PRIMARY KEY,
    Department VARCHAR(100),
    FOREIGN KEY (MID) REFERENCES LAB_MEMBER(MID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS COLLABORATOR (
    MID INT PRIMARY KEY,
    Affiliation VARCHAR(255),
    Biography TEXT,
    FOREIGN KEY (MID) REFERENCES LAB_MEMBER(MID) ON DELETE CASCADE
);

-- 3. RELATIONSHIPS
CREATE TABLE IF NOT EXISTS FUNDS (
    GID INT,
    PID INT,
    PRIMARY KEY (GID, PID),
    FOREIGN KEY (GID) REFERENCES GRANT_INFO(GID) ON DELETE CASCADE,
    FOREIGN KEY (PID) REFERENCES PROJECT(PID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS WORKS (
    PID INT,
    MID INT,
    Role VARCHAR(100),
    Hours DECIMAL(5,2),
    PRIMARY KEY (PID, MID),
    FOREIGN KEY (PID) REFERENCES PROJECT(PID) ON DELETE CASCADE,
    FOREIGN KEY (MID) REFERENCES LAB_MEMBER(MID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS USES (
    MID INT,
    EID INT,
    SDate DATE,
    EDate DATE,
    Purpose VARCHAR(255),
    PRIMARY KEY (MID, EID, SDate),
    FOREIGN KEY (MID) REFERENCES LAB_MEMBER(MID) ON DELETE CASCADE,
    FOREIGN KEY (EID) REFERENCES EQUIPMENT(EID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PUBLISHES (
    MID INT,
    PubID INT, 
    SDate DATE,
    EDate DATE,
    Purpose VARCHAR(255),
    PRIMARY KEY (MID, PubID),
    FOREIGN KEY (MID) REFERENCES LAB_MEMBER(MID) ON DELETE CASCADE,
    FOREIGN KEY (PubID) REFERENCES PUBLICATION(PubID) ON DELETE CASCADE
);

-- 4. CONSTRAINTS
ALTER TABLE PROJECT 
ADD CONSTRAINT fk_project_leader 
FOREIGN KEY (Leader) REFERENCES FACULTY(MID)
ON DELETE SET NULL
ON UPDATE CASCADE;

SET FOREIGN_KEY_CHECKS = 1;